# Generated by Django 5.1.3 on 2024-11-28 20:12

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='p_img')),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CompagnieVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='img/compagnie_vehicule', verbose_name='Image de la Compagnie')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('pays', models.CharField(choices=[('kinshasa', 'Kinshasa'), ('chine', 'Chine'), ('japon', 'Japon'), ('korea', 'Corée'), ('usa', 'États-Unis'), ('france', 'France'), ('allemagne', 'Allemagne'), ('italie', 'Italie'), ('autres', 'Autres')], default='kinshasa', max_length=100, verbose_name='Pays')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description de la Compagnie')),
                ('actif', models.BooleanField(default=False, verbose_name='Actif')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compagnies_vehicule', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('devise', models.CharField(choices=[('USD', 'USD'), ('CDF', 'CDF')], default='CDF', max_length=3, verbose_name='Devise')),
                ('motif', models.CharField(choices=[('LOCATION', 'LOCATION'), ('VENTE', 'VENTE')], default='LOCATION', max_length=8, verbose_name='Motif')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('image_profile', models.ImageField(blank=True, null=True, upload_to='vehicule/images/', verbose_name='Image principale')),
                ('image_galerie', models.ImageField(blank=True, null=True, upload_to='vehicule/galerie/', verbose_name='Image galerie')),
                ('contacté', models.BooleanField(default=False, verbose_name='Contacté')),
                ('type_bien', models.CharField(choices=[('voiture', 'Voiture'), ('moto', 'Moto'), ('camion', 'Camion'), ('bus', 'Bus'), ('utilitaire', 'Véhicule utilitaire'), ('autres', 'Autres')], default='voiture', max_length=50, verbose_name='Type de bien')),
                ('commune', models.CharField(choices=[('ngaliema', 'Ngaliema'), ('limete', 'Limete'), ('mongafula', 'Mongafula'), ('kingabwa', 'Kingabwa'), ('bandalungwa', 'Bandalungwa'), ('kinshasa', 'Kinshasa'), ('gombe', 'Gombe'), ('kasa-vubu', 'Kasa-Vubu'), ('ngiri-ngiri', 'Ngiri-Ngiri'), ('kinkole', 'Kinkole'), ('matete', 'Matete'), ('kinshasa', 'Kinshasa'), ('kimbanguiste', 'Kimbanguiste'), ('kalamu', 'Kalamu'), ('ngaba', 'Ngaba'), ('lemba', 'Lemba'), ('madrassah', 'Madrassah'), ('masina', 'Masina'), ('lualaba', 'Lualaba'), ('kwa-kabuya', 'Kwa-Kabuya'), ('makala', 'Makala'), ('bumbu', 'Bumbu'), ('ngombé', 'Ngombé'), ('eala', 'Eala')], default='kinshasa', max_length=100, verbose_name='Commune')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicule/galerie/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='ContactVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Message ou description')),
                ('contacté', models.BooleanField(default=False, verbose_name='Contacté')),
                ('date_contact', models.DateTimeField(auto_now_add=True, verbose_name='Date de la demande')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.vehicule', verbose_name='Bien immobilier')),
            ],
            options={
                'verbose_name': 'Demande de Contact',
                'verbose_name_plural': 'Demandes de Contact',
                'ordering': ['-date_contact'],
            },
        ),
        migrations.CreateModel(
            name='VehiculeCompagnie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('devise', models.CharField(choices=[('USD', 'USD'), ('CDF', 'CDF')], default='CDF', max_length=3, verbose_name='Devise')),
                ('motif', models.CharField(choices=[('LOCATION', 'LOCATION'), ('VENTE', 'VENTE')], default='LOCATION', max_length=8, verbose_name='Motif')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('image_profile', models.ImageField(blank=True, null=True, upload_to='vehicule_compagnie/images/', verbose_name='Image principale')),
                ('image_galerie', models.ImageField(blank=True, null=True, upload_to='vehicule_compagnie/galerie/', verbose_name='Image galerie')),
                ('contacté', models.BooleanField(default=False, verbose_name='Contacté')),
                ('type_bien', models.CharField(choices=[('voiture', 'Voiture'), ('moto', 'Moto'), ('camion', 'Camion'), ('bus', 'Bus'), ('utilitaire', 'Véhicule utilitaire'), ('autres', 'Autres')], default='voiture', max_length=50, verbose_name='Type de bien')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='core.compagnievehicule', verbose_name='Compagnie')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicule_compagnies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoCompagnie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicule_compagnie/galerie/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vehicule_compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.vehiculecompagnie')),
            ],
        ),
        migrations.CreateModel(
            name='ContactVehiculeCompagnie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Message ou description')),
                ('contacté', models.BooleanField(default=False, verbose_name='Contacté')),
                ('date_contact', models.DateTimeField(auto_now_add=True, verbose_name='Date de la demande')),
                ('vehicule_compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.vehiculecompagnie', verbose_name='Compagnie de véhicules')),
            ],
            options={
                'verbose_name': 'Demande de Contact',
                'verbose_name_plural': 'Demandes de Contact',
                'ordering': ['-date_contact'],
            },
        ),
    ]
